name: nitm_mobile
description: NITM internal mobile app (starter)
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  firebase_messaging: ^14.6.0
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_linter: any

flutter:
  uses-material-design: true

